openapi: 3.1.0
info:
  title: API сервер для личного проекта «Шесть городов».
  description: |-
    * Список ресурсов и маршрутов сервера «Шесть городов».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
tags:
  - name: offers
    description: Действия с объявлениями.
  - name: serviсes
    description: Действия с сервисами.
  - name: comments
    description: Действия с комментариями.
  - name: users
    description: Действия с пользователем.