export type MockServerData = {
    titles: string[];
    descriptions: string[];
    postDates: string[];
    cities: string[];
    previews: string[];
    images: string[];
    proStatuses: string[];
    favouriteStatuses: string[];
    ratings: string[];
    housingTypes: string[];
    countRooms: string[];
    countGuests: string[];
    prices: string[];
    services: string[];
    firstnames: string[];
    emails: string[];
    avatarPaths: string[];
    //passwords: string[];
    typeUsers: string[];
    commentsCounts: string[];
    latitudes: string[];
    longitudes: string[];
};
